# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MtxProd <- function(A, B) {
    .Call(`_COCA_MtxProd`, A, B)
}

expit <- function(x) {
    .Call(`_COCA_expit`, x)
}

